import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "釈迦遺 Vton Page | Create Next App",
  description: "Generated by create next app",
};

export default function TryOnLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
